== RedHat Cloud Services frontend components - components

https://badge.fury.io/js/%40redhat-cloud-services%2Ffrontend-components[image:https://badge.fury.io/js/%40redhat-cloud-services%2Ffrontend-components.svg[npm version]]

This package consists of shared components required by RedHat Cloud Services team.

=== Installation

With npm

[source,bash]
----
npm i -S @redhat-cloud-services/frontend-components
----

With yarn

[source,bash]
----
yarn add @redhat-cloud-services/frontend-components
----

This package is dependent on https://www.npmjs.com/package/@redhat-cloud-services/frontend-components-utilities[@redhat-cloud-services/frontend-components-utilities] and will automatically install it trough direct dependencies.

=== Migration v2 -> v3

==== Direct imports path changes

* Remove `cjs` or `esm` from your import paths.
* Remove the `components` fragment from your import path
* Modules now have default value

[source,jsx]
----
// v2
import { Ansible } from '@redhat-cloud-services/frontend-components/components/cjs/Ansible';

// v3
import Ansible from '@redhat-cloud-services/frontend-components/Ansible';
/** OR */
import { Ansible } from '@redhat-cloud-services/frontend-components/Ansible';
----

==== Importing styles is no longer required

Importing CSS for components is no longer required. Components import their styling whenever they are rendered for the first time.

[source,diff]
----
-@import '~@redhat-cloud-services/frontend-components/index.css';
----

[[sub-components-imports]]
==== Sub components imports.

When importing a partial component like `TextFilter` from `ConditionalFilter`, use direct import shorthand from `ConditionalFilter`. Do not import from `TextFilter` file directly! All imports must have at most only one level!

[source,jsx]
----
// OK
import { X } from '@redhat-cloud-services/frontend-components/<ModuleName>'
// Wrong!!
import X from '@redhat-cloud-services/frontend-components/<ModuleName>/X'

----

Deeper imports will break automatic csj/esm module resolution.

=== Treeshaking

In order not to improve your bundle size you you should either import components trough direct imports or use babel plugin to change relative imports to direct imports. You can mix both direct imports and babel plugin, it's just convenient to use the babel plugin so you don't have to change all of your imports.

==== Direct imports

For speedy build times, you can use direct import paths For instance `tableToolbar` can be imported as:

[source,JSX]
----
import TableToolbar from '@redhat-cloud-services/frontend-components/TableToolbar';
----

You can also use shorthand imports.

==== Babel plugins

There are 2 plugins that can be used to change relative imports to direct imports

* https://www.npmjs.com/package/babel-plugin-import[babel-plugin-import] - easy setup, however not that extensible
* https://www.npmjs.com/package/babel-plugin-transform-imports[babel-plugin-transform-imports] - harder to setup, but allows custom rules

Since our components require a bit more setting up, we are recommending using `babel-plugin-transform-imports`.

Change your babel config to be javascript config `babel.config.js` so you can use JS functions to properly transform your imports. Not every component has its own directory. You can use mapper to map component name to directory.

[source,JS]
----
const FECMapper = {
    SkeletonSize: 'Skeleton',
    PageHeaderTitle: 'PageHeader'
};

module.exports = {
    presets: [
        // your presets go here
    ],
    plugins: [
        // your plugins
        [
            'transform-imports',
            {
              '@redhat-cloud-services/frontend-components': {
                transform: (importName) =>
                  `@redhat-cloud-services/frontend-components/${FECMapper[importName] || importName}`,
                preventFullImport: false,
                skipDefaultConversion: true
              }
            },
            'frontend-components'
        ]
        // other plugins, for instance PF transform imports and such as well
    ]
};
----

As with direct imports you can choose between `esm` and `cjs` output.

[source,JS]
----
// cjs
transform: (importName) =>`@redhat-cloud-services/frontend-components/${FECMapper[importName] || importName}`,
// esm
transform: (importName) =>`@redhat-cloud-services/frontend-components/esm/${FECMapper[importName] || importName}`,

----

=== Documentation Links

* Components
** link:doc/sample.md[sample]
** link:doc/page_header.md[page_header]
** link:doc/tabLayout.md[tabLayout]
** link:doc/emptyTable.md[emptyTable]
** link:doc/input.md[input]
** link:doc/dropdown.md[dropdown]
** link:doc/longTextTooltip.md[longTextTooltip]
** link:doc/spinner.md[spinner]
** link:doc/ansible.md[ansible]
** link:doc/filters.md[filters]
** link:doc/battery.md[battery]
** link:doc/shield.md[shield]
** link:doc/table.md[table]
** link:doc/truncate.md[truncate]
** link:doc/tableToolbar.md[tableToolbar]
** link:doc/wizard.md[wizard]
** link:doc/pagination.md[pagination]
** link:doc/treeview-table.md[treeview-table]
** link:doc/section.md[section]
** link:doc/dark.md[dark]
** link:doc/breadcrumbs.md[breadcrumbs]
** link:doc/reboot.md[reboot]
